# Generated by Django 3.0.4 on 2020-03-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0003_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='earnings',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
