# Generated by Django 3.0.3 on 2020-03-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0004_profile_earnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='created_by',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
